name: islamyat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0-246.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
#  cupertino_icons: ^1.0.2
#  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  dio: ^5.3.0
  conditional_builder_null_safety: ^0.0.6
#  fluttertoast: ^8.2.2
#  image_picker: ^1.0.0
    #  google_maps_flutter: ^2.3.1
#  toggle_switch: ^2.1.0
#  date_format: ^2.0.7
  intl: ^0.18.1
  introduction_screen: ^3.1.11
  convex_bottom_bar: ^3.2.0
  flutter_svg: ^2.0.7
  hijri: ^3.0.0
  adhan_dart: ^1.0.8
  location: ^5.0.3
  flutter_qiblah: ^2.2.0
  geolocator: ^9.0.2
  arabic_numbers: ^1.0.0
  scrollable_positioned_list: ^0.2.3
  google_fonts: ^5.1.0
  share_plus: ^4.0.3
  url_launcher: ^6.1.6
#  background_fetch: ^1.2.1
#  flutter_background_service: ^5.0.1
#  overlay_support: ^2.1.0
#  flutter_barcode_scanner: ^2.0.0
#  scroll_positioned: ^0.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/json/
  fonts:
    - family: quran
      fonts:
        - asset: assets/fonts/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
